export const imgSource = {
    slide1: require('./slide-1.png'),
    slide2: require('./slide-2.png'),
    slide3: require('./slide-3.png'),
    slide4: require('./slide-4.png'),
    slide5: require('./slide-5.png'),
    slide6: require('./slide-6.png'),
    product1: require('./product-1.png'),
    product2: require('./product-2.png'),
    product3: require('./product-3.png'),
    product4: require('./product-4.png'),
    product5: require('./product-5.png'),
    product6: require('./product-6.png'),
    product7: require('./product-7.png'),
    product8: require('./product-8.png'),
    product9: require('./product-9.png'),
    product10: require('./product-10.png'),
    product11: require('./product-11.png'),
    product12: require('./product-12.png'),
    banner1: require('./banner-1.png'),
    banner2: require('./banner-2.png'),
    banner3: require('./banner-3.png'),
    banner4: require('./banner-4.png'),
    banner5: require('./banner-5.png'),
    banner6: require('./banner-6.png'),
    logo: require('./logo.png'),
    logofooter: require('./logo-footer.png'),
}